[tool.poetry]
name = "001"
version = "0.1.0"
description = ""
authors = ["10856045 <10856045@ntub.edu.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
